name: salonmate
description: "salonmate Application"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # core
  http: ^1.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  logger: ^2.2.0
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.7.0
  geolocator: ^13.0.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  onesignal_flutter: ^5.1.0
  pdf: ^3.11.3
  open_filex: ^4.6.0
  internet_connection_checker_plus: ^2.7.0

  # utility
  url_launcher: ^6.1.6
  flutter_svg: ^2.0.10+1
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  generate: true
 
  uses-material-design: true

  assets:
    # logo
    - assets/logo/
    # icons
    - assets/icons/
    # images
    - assets/images/

  fonts:
    - family: Inter Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Inter Black
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf