name: salonmate
description: "salonmate Application"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # core
  flutter_background_service: ^5.0.10
  workmanager: ^0.5.2
  http: ^1.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  logger: ^2.2.0
  package_info_plus: ^4.2.0
  flutter_spinkit: ^5.2.1
  permission_handler: ^11.3.1
  data_connection_checker_nulls: ^0.0.2
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.7.0
  qr_flutter: ^4.1.0

  # utility
  url_launcher: ^6.1.6
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.10+1
  another_flushbar: ^1.12.30
  flutter_datetime_picker_plus: ^2.2.0
  autocomplete_textfield: ^2.0.1
  table_calendar: ^3.0.9
  animate_do: ^3.3.4
  flutter_pdfview: ^1.3.2
  carousel_slider_plus: ^7.0.0
  cached_network_image: ^3.3.1
  contained_tab_bar_view: ^0.8.0
  water_drop_nav_bar: ^2.2.2
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8


flutter:

 
  uses-material-design: true

  
  assets:
    # logo
    - assets/logo/
    # icons
    - assets/icons/
    # images
    - assets/images/

  fonts:
    - family: Inter Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Inter Black
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
